name       : ansilove
version    : 4.0.0
release    : 3
source     :
    - https://github.com/ansilove/ansilove/releases/download/4.0.0/ansilove-4.0.0.tar.gz : 2107a7bcb1b69f65924eb00acafce537ed049b92b84582202408ab3b86f02ea1
license    : BSD-2-Clause
component  : multimedia.graphics
summary    : ANSI / ASCII art to PNG converter in C
description: |
    ANSI / ASCII art to PNG converter in C
builddeps  :
    - libansilove-devel
setup      : |
    %cmake .
build      : |
    %make -Wno-unused-result
install    : |
    %make_install
