name       : ansilove
version    : 4.0.6
release    : 5
source     :
    - https://github.com/ansilove/ansilove/archive/4.0.6.tar.gz : 9a11a48d5f53b85395facf7676753e7b276195d101ae71977789c39d49483282
homepage   : https://www.ansilove.org
license    : BSD-2-Clause
component  : multimedia.graphics
summary    : ANSI and ASCII art to PNG converter in C
description: |
    ansilove converts ANSi and artscene related file formats into PNG images.
builddeps  :
    - libansilove-devel
setup      : |
    %cmake .
build      : |
    %make -Wno-unused-result
install    : |
    %make_install
