name       : ansilove
version    : 3.0.4
release    : 1
source     :
    - https://github.com/ansilove/ansilove/archive/3.0.4.tar.gz : b115242186e7e5d98311b49c57503cf8dbe6955cbc9880fb3ef7ad831d1f03de
license    : BSD-2-Clause
component  : multimedia.graphics
summary    : ANSi / ASCII art to PNG converter in C
description: |
    ANSi / ASCII art to PNG converter in C
builddeps  :
    - pkgconfig(gdlib)
setup      : |
    sed -i 's:-Werror ::g' CMakeLists.txt
    %cmake .
build      : |
    %make -Wno-unused-result
install    : |
    %make_install
