name       : ansilove
version    : 4.1.0
release    : 6
source     :
    - https://github.com/ansilove/ansilove/archive/4.1.0.tar.gz : 2c9c1b4f284d4a255ef389f50bb28d327e67c91d39293e07579ce3a186ce2af0
homepage   : https://www.ansilove.org
license    : BSD-2-Clause
component  : multimedia.graphics
summary    : ANSI and ASCII art to PNG converter in C
description: |
    ansilove converts ANSi and artscene related file formats into PNG images.
builddeps  :
    - libansilove-devel
setup      : |
    %cmake .
build      : |
    %make -Wno-unused-result
install    : |
    %make_install
