name       : ansilove
version    : 4.1.6
release    : 9
source     :
    - https://github.com/ansilove/ansilove/releases/download/4.1.6/ansilove-4.1.6.tar.gz : acc3d6431cdb53e275e5ddfc71de5f27df2f2c5ecc46dc8bb62be9e6f15a1cd0
homepage   : https://www.ansilove.org
license    : BSD-2-Clause
component  : multimedia.graphics
summary    : ANSI and ASCII art to PNG converter in C
description: |
    ansilove converts ANSi and artscene related file formats into PNG images.
builddeps  :
    - libansilove-devel
setup      : |
    %cmake .
build      : |
    %make -Wno-unused-result
install    : |
    %make_install
