name       : ansilove
version    : 3.0.9
release    : 2
source     :
    - https://github.com/ansilove/ansilove/releases/download/3.0.9/ansilove-3.0.9.tar.gz : 3117b083f3a97da6f3d24963d46b83af2fb6967c5c33940d0b097386f338b919
license    : BSD-2-Clause
component  : multimedia.graphics
summary    : ANSI / ASCII art to PNG converter in C
description: |
    ANSI / ASCII art to PNG converter in C
builddeps  :
    - pkgconfig(gdlib)
setup      : |
    %cmake .
build      : |
    %make -Wno-unused-result
install    : |
    %make_install
